### ISSUE TITLE
The requested resource was not found on this service

### ISSUE THREAD

**Issue by ranglang** [ablator/ablator#132]
i run service but fail to get api service

http://10.168.2.129:8001/api/v3/928afed-c3c9-4064-892d-82fc5c298b84/dd/caniuse/

<h1>Not Found</h1><p>The requested resource was not found on this server.</p>

**Comment by winsmith** [comment]
Check out the `/dd/` in your URL... that seems off. Does it work if you remove that part of the URL?

**Comment by ranglang** [comment]
ok , i just
